version: "3.9"
services:
  typescriptmate-api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - /home/ubuntu/models/typescriptmate:/app/model
